spring.application.name=news24h-backend

# ==============================
# SERVER CONFIG
# ==============================
server.port=8080

# ==============================
# DATABASE CONFIG (MySQL 8)
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3307/news24hdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# JWT CONFIG
# ==========================================
app.jwt.secret=S04dI5K9vPxl2Q1Zt8C3kF6JH9nR4mW0bY7eU2qT5aV8cG1sM0dP2nL4qA6hD9
app.jwt.expiration-ms=86400000

# ==========================================
# GEMINI API
# ==========================================
gemini.api-key=AIzaSyCNHlelaw92swJ0yBgpINjPF2iZYZTbbps
gemini.model=gemini-2.5-flash
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/${gemini.model}:generateContent

